#! /usr/bin/env bash

set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

dir="$(dirname "$0")"
root="$(cd "$dir"; cd ..; pwd)"
user_dir="$root/apps/user_app"
chat_dir="$root/apps/chat_app"

print() { echo -e "\n${RED}==>${RESET} ${GREEN}$1${RESET}"; }

install_deps() {
  print "Installing dependencies ..."
  mix local.rebar --force
  mix deps.get
}

compile_apps() {
  print "Compiling apps ..."
  mix compile
}

setup_user_app() {
  print "Setting up User app ..."
  cd "$user_dir" && mix ecto.setup && cd "$root"
}

setup_chat_app() {
  print "Setting up Chat app ..."
  cd "$chat_dir" && yarn && cd "$root"
}

install_deps
compile_apps
setup_user_app
setup_chat_app

print "Run ex-chat with ./script/run\n"
