#! /usr/bin/env bash

set -e

ROOT="$(cd "$(dirname $0)"; cd ..; pwd)"
USER_DIR="$ROOT/apps/user_app"
CHAT_DIR="$ROOT/apps/chat_app"

source "$ROOT/scripts/logger"

install_deps() {
  log 'Installing dependencies ...'
  mix local.rebar --force
  mix deps.get
}

compile_apps() {
  log 'Compiling apps ...'
  mix compile
}

setup_user_app() {
  log 'Setting up User app ...'
  cd "$USER_DIR" && mix ecto.setup && cd "$ROOT"
}

setup_chat_app() {
  log 'Setting up Chat app ...'
  cd "$CHAT_DIR" && yarn && cd "$ROOT"
}

install_deps
compile_apps
setup_user_app
setup_chat_app

log 'Run ex-chat with ./script/start'
