#! /usr/bin/env bash

set -e

ROOT="$(cd "$(dirname $0)"; cd ..; pwd)"
USER_DIR="$ROOT/apps/user_app"
CHAT_DIR="$ROOT/apps/chat_app"

source "$ROOT/scripts/logger"

log 'Configuring applications ...'

cd "$USER_DIR"
mix phoenix.server &>> ./dev.log &
log 'User application started'

cd "$CHAT_DIR"
mix phoenix.server &>> ./dev.log &
log 'Chat application started'

log 'Run ./scripts/stop to stop servers'
